### ISSUE TITLE
No 1080-skin

### ISSUE THREAD

**Issue by RobvanderDoes** [Dima73/enigma2-plugin-extensions-tmbd#1]
Attached the screens for a 1080-skin.
You'll have to embed it into the source file, including the correct coding for choosing of the correct sized screens.
Sorry I can't do the latter myself.
[TMBD_1080-screens.zip](https://github.com/Dima73/enigma2-plugin-extensions-tmbd/files/444428/TMBD_1080-screens.zip)

**Comment by Dima73** [comment]
Many thanks.

**Comment by RobvanderDoes** [comment]
You closed it, but you still didn't embed the 1080 screens....

**Comment by Dima73** [comment]
https://github.com/Dima73/enigma2-plugin-extensions-tmbd/blob/master/src/plugin.py#L342
