### ISSUE TITLE
YT-Feeds Problem

### ISSUE THREAD

**Issue by lanagalice** [Dima73/enigma2-plugin-extensions-tmbd#35]
there is problem with YTrailer-Feeds

whenever searching for event to get trailer, I got that message
"Problems with YT-Feeds!"

any solution please

**Comment by Dima73** [comment]
Related https://github.com/Taapat/enigma2-plugin-youtube

**Comment by fairbird** [comment]
@Dima73 
You need to update compat.py as lasted update of Taapat file
https://github.com/Dima73/enigma2-plugin-extensions-tmbd/blob/master/src/compat.py

**Comment by Dima73** [comment]
It's been done for a long time
[Update YouTubeVideoUrl to fix trailer playback](https://github.com/Dima73/enigma2-plugin-extensions-tmbd/commit/6b29d9fe7d777ea9ab9ef6ad9eef171d6271120b)

**Comment by fairbird** [comment]
It was more updated you did not apply it... So YTrailer does not work any more (Problems with YT-Feeds!)
https://github.com/Taapat/enigma2-plugin-youtube/blob/master/src/compat.py#L35-L60
Or . There are different codes need to be update.

**Comment by lanagalice** [comment]
Still no updates !!
I tried my best to find solution but sadly I couldn't

Can you speak with Taapat to find solution

**Comment by lanagalice** [comment]
Thanks Taapat 
We love you
Fixed and working
