### ISSUE TITLE
YT error

### ISSUE THREAD

**Issue by frank087234** [Dima73/enigma2-plugin-extensions-tmbd#5]
Error :Problems with YT feeds, on channels on sat 28.2E (BSkyB).. but works fine with other satellites!

**Comment by Dima73** [comment]
Maybe incorrect encoding for EPG?

**Comment by frank087234** [comment]
Possible because it happens with open satellite epg, with rytec it is ok, but the problem, when play channel, the rytec epg is replaced by the satellite epg ( which has the problem )

**Comment by Dima73** [comment]
I can not fix this problem.
