### ISSUE TITLE
Long press EPG on a service that has no EPG information

### ISSUE THREAD

**Issue by pr2git** [Dima73/enigma2-plugin-extensions-tmbd#7]
Hi,

Start watching a channel that has EPG information.
Go into the channel list and stay on a service that doesn't have EPG information (do not zap to it just highlight it) perform a long press on the EPG button.
In the menu select:  TMBD details for the event
It will search for the event on the channel with EPG and not for the channel that has no EPG (logical since no EPG, no search them).

Expected behavior:
You already implement that when there is no EPG data it is the Service Name which is used to search with TMBD I would like to this behavior too when we do a long press on EPG on an entry without EPG.
So please display: TMBD search when we perform a long press on EPG button on service without EPG instead of TMBD details for the event (since there is no event) in the channel list.

Thanks,

Pr2

**Comment by Dima73** [comment]
Sorry, I will not do it.
This is a very individual opportunity.

**Comment by pr2git** [comment]
This is just the same as you already does, when we are in the channel list on a service that has no EPG then you use the service name to search for (this is already done).
I am looking for a way to have this just by pressing 1 key, I try with Hotkey assigning long press but it doesn't work, in Hotkey if I select TMBD Details it open up the setup screen and not doesn't search for the service name. So this is not something new, just a logical extension of what is already done.

**Comment by Dima73** [comment]
`Hotkey if I select TMBD Details it open up the setup screen`

'Show \"TMBD Details: current event\" in extensions menu' YES and set as Hotkey

**Comment by pr2git** [comment]
It doesn't work, nothing happens, there is no fallback to the service name when there is no EPG event.
If I am in the channel list on a service without EPG, in the menu it is TMBD Details  that is displayed and this is working fine it is using service name as fallback.
If I launch the movie and press the assigned Hotkey, then TMBD is open up but display nothing since it doesn't use the service name has fallback.

**Comment by Dima73** [comment]
https://github.com/Dima73/enigma2-plugin-extensions-tmbd/commit/7e5bdaaa83e53986f7027020579a7ed13402ced4

**Comment by pr2git** [comment]
Hi,
Thanks for the change it is working fine now.
I just discovered that it is not possible to have the Hotkey working while the Channel List selection is open but this is not linked with your plugin so I will close this issue.
Pr2
