### ISSUE TITLE
poster preview

### ISSUE THREAD

**Issue by norhap** [Dima73/enigma2-plugin-extensions-tmbd#8]
Hi.
@Dima73 I have this problem I explain my scenario:
mount NFS NAS path /media/net /movie
I have all the necessary files for your plugin to read the poster, but it does not, I have .meta, .jpg files etc ... but there is no way. (EMC read cover-poster from MovieSelection no problem).

Another problem, when I deactivate poster preview if I return to movieselection and return to settings (key MENU MovieSelection), then it appears again (black poster screen since as I indicated above it does not read me the data of the service poster)
view photo:
<a href="https://ibb.co/jR3QR7S"><img src="https://i.ibb.co/YZf1Zvx/dima.jpg" alt="dima" border="0"></a>

**Comment by Dima73** [comment]
1)network devices are not supported
2)this is a known problem, I do not know the solution

**Comment by norhap** [comment]
Thanks, I was unaware that there were problems with network files.
