### ISSUE TITLE
Search Trailer does not work !!

### ISSUE THREAD

**Issue by fairbird** [Dima73/enigma2-plugin-extensions-tmbd#9]
I have got error with trying to use Search Trailer ..
`Problems with YT-Feeds!`

and Some times I have got crash error

> < 52357.4489> 01:09:02.4488 2020-06-30 01:09:02+0300 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/TMBD/tmbdYTTrailer.py", line 247, in errorTaimerStop
< 52357.4494> 01:09:02.4494 2020-06-30 01:09:02+0300 [-]     self.showError()
< 52357.4498> 01:09:02.4497 2020-06-30 01:09:02+0300 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/TMBD/tmbdYTTrailer.py", line 252, in showError
< 52357.4503> 01:09:02.4503 2020-06-30 01:09:02+0300 [-]     self.session.open(MessageBox, _('Problems with YT-Feeds!'), MessageBox.TYPE_INFO)
< 52357.4507> 01:09:02.4507 2020-06-30 01:09:02+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 349, in open
< 52357.4512> 01:09:02.4512 2020-06-30 01:09:02+0300 [-]     raise RuntimeError("modal open are allowed only from a screen which is modal!")
< 52357.4516> 01:09:02.4516 2020-06-30 01:09:02+0300 [-] RuntimeError: modal open are allowed only from a screen which is modal!

**Comment by Dima73** [comment]
https://github.com/Dima73/enigma2-plugin-extensions-tmbd/commit/305aaafc15d7dd611ac48ef5cbfa48a2f7daab15
